---
- name: python3 installed
  apt:
    name: python3
    update_cache: yes
    state: latest

- name: certbot installed
  apt:
    name: "python3-certbot-apache"
    update_cache: yes
    state: latest
  register: certbot

# todo: optional email instead of --register-unsafely-without-email
- name: certbot apache
  command: >-
    certbot
    --apache
    -d {{ PUBLIC_HOSTNAME }}
    --agree-tos
    --register-unsafely-without-email
    --noninteractive
    --redirect
  when: certbot

# todo: check if quiet or noninteractive are needed
- name: certbot crontab
  ansible.builtin.cron:
    name: certbot
    user: root
    special_time: monthly
    job: "/usr/bin/certbot renew"
  when: certbot
