---
- name: python3 installed
  apt:
    name: python3
    update_cache: yes
    state: latest

- name: certbot installed
  apt:
    name: "python3-certbot-apache"
    update_cache: yes
    state: latest
  register: certbot

- name: certbot apache
  command: >-
    certbot
    --apache
    -d {{ PUBLIC_HOST }}
    --agree-tos
    -m {{ EXPIRATION_EMAIL }}
    --noninteractive
    --redirect
  when: certbot

- name: certbot crontab
  ansible.builtin.cron:
    name: certbot
    user: root
    special_time: monthly
    job: "/usr/bin/certbot renew"
  when: certbot
