---
- name: 1. install Apache
  apt: name=apache2 state=present

# for raspbian: php7.4, for Ubunto 21.10: php8.0
- name: 2. install PHP module for Apache
  apt: name=libapache2-mod-php8.0 state=present

- name: 3. start Apache
  service: name=apache2 state=started enabled=yes

- name: 4. install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664
