---
- name: NodeJS
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - nodejs
    - npm

- name: naf user
  user:
    name: "{{ NAF_USER }}"
    create_home: yes

- name: naf server directory
  file:
    path: "{{ NAF_SERVER_DIR }}"
    owner: "{{ NAF_USER }}"
    mode: 0755
    state: directory

# also need /home/naf/.ansible/tmp

# possible error: package-lock.json is changed - update: false fixed it
- name: naf code
  become: yes
  become_user: "{{ NAF_USER }}"
  git:
    repo: "{{ NAF_REPO_URL }}"
    dest: "{{ NAF_SERVER_DIR }}"
    update: false

- name: naf node modules
  become: yes
  become_user: "{{ NAF_USER }}"
  npm:
    path: "{{ NAF_SERVER_DIR }}"

- name: naf build
  become: yes
  become_user: "{{ NAF_USER }}"
  command:
    cmd: npm run build
    chdir: "{{ NAF_SERVER_DIR }}"

# naf will be started by pm2 later on

# maybe separate role for this
- name: mod proxy
  community.general.apache2_module:
    name: "{{ item }}"
  with_items:
  - proxy
  - proxy_http

# todo regex to place at correct line
- name: proxy to naf
  blockinfile:
    path: /etc/apache2/sites-available/000-default-le-ssl.conf
    block: |
      ProxyPass "/" "http://localhost:8080/"
      ProxyPassReverse "/" "http://localhost:8080/"
    marker: "# {mark} ANSIBLE MANAGED BLOCK proxy naf"

- name: node pm2
  npm:
    name: pm2
    global: yes

- name: pm2 systemd service
  command:
    cmd: >-
      sudo
      env
      PATH=$PATH:/usr/bin
      /usr/local/lib/node_modules/pm2/bin/pm2
      startup
      systemd
      -u {{ NAF_USER }}
      --hp /home/{{ NAF_USER }}
    creates: /etc/systemd/system/pm2-{{ NAF_USER }}.service

- name: delete previous pm2 processes
  become: yes
  become_user: "{{ NAF_USER }}"
  command: pm2 delete all

# mabe startOrReload
- name: start naf
  become: yes
  become_user: "{{ NAF_USER }}"
  command: >-
    pm2
    start
    -f
    --cwd {{ NAF_SERVER_DIR }}
    {{ NAF_APP_PATH }}

- name: save naf service
  become: yes
  become_user: "{{ NAF_USER }}"
  command: "pm2 save"
