# Adjust the fan speed minimizing noise
---
- name: The raspi fan systemd config
  copy:
    src: raspi-fan.service
    dest: /etc/systemd/system
    mode: 0644
  notify: Start raspi fan

- name: The fan control logic script
  copy:
    src: raspi-fan.py
    dest: /usr/local/sbin/raspi-fan.py
    mode: 0744
  notify: Start raspi fan
